DECLARE
v_col_cnt INTEGER;
-- Adiciona a coluna DATA_REGISTRO se ela ainda não existir
IF COL_LENGTH('TB_MOTO', 'DATA_REGISTRO') IS NULL
BEGIN
ALTER TABLE TB_MOTO
    ADD DATA_REGISTRO DATETIME NOT NULL DEFAULT GETDATE();
END
GO

-- Atualiza linhas antigas (onde DATA_REGISTRO estiver nula)
UPDATE TB_MOTO
SET DATA_REGISTRO = GETDATE()
WHERE DATA_REGISTRO IS NULL;
GO
