
-- ===================================================
-- CONSTRAINTS, INDEXES para SQL Server
-- ===================================================

-- ===== FKs =====
ALTER TABLE TB_ESTADO ADD CONSTRAINT FK_ESTADO_PAIS
    FOREIGN KEY (ID_PAIS) REFERENCES TB_PAIS(ID_PAIS);

ALTER TABLE TB_CIDADE ADD CONSTRAINT FK_CIDADE_ESTADO
    FOREIGN KEY (ID_ESTADO) REFERENCES TB_ESTADO(ID_ESTADO);

ALTER TABLE TB_MOTO ADD CONSTRAINT FK_MOTO_CLIENTE
    FOREIGN KEY (ID_CLIENTE) REFERENCES TB_CLIENTE(ID_CLIENTE);

ALTER TABLE TB_MOTO ADD CONSTRAINT FK_MOTO_MODELO
    FOREIGN KEY (ID_MODELO_MOTO) REFERENCES TB_MODELO_MOTO(ID_MODELO_MOTO);

ALTER TABLE TB_BEACON ADD CONSTRAINT FK_BEACON_MOTO
    FOREIGN KEY (ID_MOTO) REFERENCES TB_MOTO(ID_MOTO);

ALTER TABLE TB_BEACON ADD CONSTRAINT FK_BEACON_MODELO
    FOREIGN KEY (ID_MODELO_BEACON) REFERENCES TB_MODELO_BEACON(ID_MODELO_BEACON);

ALTER TABLE TB_MOVIMENTACAO ADD CONSTRAINT FK_MOV_MOTO
    FOREIGN KEY (ID_MOTO) REFERENCES TB_MOTO(ID_MOTO);

ALTER TABLE TB_MOVIMENTACAO ADD CONSTRAINT FK_MOV_TIPO
    FOREIGN KEY (ID_TIPO_MOVIMENTACAO) REFERENCES TB_TIPO_MOVIMENTACAO(ID_TIPO_MOVIMENTACAO);

ALTER TABLE TB_LOCALIZACAO ADD CONSTRAINT FK_LOC_MOTO
    FOREIGN KEY (ID_MOTO) REFERENCES TB_MOTO(ID_MOTO);

ALTER TABLE TB_LOCALIZACAO ADD CONSTRAINT FK_LOC_PATIO
    FOREIGN KEY (ID_PATIO) REFERENCES TB_PATIO(ID_PATIO);

ALTER TABLE TB_REGISTRO_BATERIA ADD CONSTRAINT FK_REG_BAT_BEACON
    FOREIGN KEY (ID_BEACON) REFERENCES TB_BEACON(ID_BEACON);

ALTER TABLE TB_USUARIO ADD CONSTRAINT FK_USUARIO_TIPO
    FOREIGN KEY (ID_TIPO_USUARIO) REFERENCES TB_TIPO_USUARIO(ID_TIPO_USUARIO);

-- ===== UNIQUE / CHECK =====
CREATE UNIQUE INDEX UX_MOTO_PLACA ON TB_MOTO(PLACA);
CREATE UNIQUE INDEX UX_BEACON_UUID ON TB_BEACON(UUID);

ALTER TABLE TB_BEACON ADD CONSTRAINT UQ_BEACON_MOTO UNIQUE (ID_MOTO);

ALTER TABLE TB_BEACON ADD CONSTRAINT CHK_BEACON_BATERIA CHECK (BATERIA BETWEEN 0 AND 100);

-- ===== INDEXES auxiliares =====
CREATE INDEX IX_MOV_MOTO ON TB_MOVIMENTACAO(ID_MOTO);
CREATE INDEX IX_LOC_MOTO ON TB_LOCALIZACAO(ID_MOTO);
CREATE INDEX IX_BEACON_MODELO ON TB_BEACON(ID_MODELO_BEACON);
CREATE INDEX IX_MOTO_MODELO ON TB_MOTO(ID_MODELO_MOTO);