-- Adiciona colunas usadas pelo JPA/DataLoader em TB_CLIENTE
ALTER TABLE TB_CLIENTE ADD (
  CPF           VARCHAR2(14),
  DATA_CADASTRO TIMESTAMP,
  EMAIL         VARCHAR2(120),
  TELEFONE      VARCHAR2(20)
);


CREATE UNIQUE INDEX UX_CLIENTE_EMAIL ON TB_CLIENTE (EMAIL);


