-- Adiciona colunas uma a uma (evita erro se já existirem)
IF COL_LENGTH('TB_CLIENTE', 'CPF') IS NULL
BEGIN
ALTER TABLE TB_CLIENTE ADD CPF VARCHAR(14);
END

IF COL_LENGTH('TB_CLIENTE', 'DATA_CADASTRO') IS NULL
BEGIN
ALTER TABLE TB_CLIENTE ADD DATA_CADASTRO DATETIME;
END

IF COL_LENGTH('TB_CLIENTE', 'EMAIL') IS NULL
BEGIN
ALTER TABLE TB_CLIENTE ADD EMAIL VARCHAR(120);
END

IF COL_LENGTH('TB_CLIENTE', 'TELEFONE') IS NULL
BEGIN
ALTER TABLE TB_CLIENTE ADD TELEFONE VARCHAR(20);
END
